version: "3.9"
services:
  spring-app:
    container_name: spring-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/project
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    networks:
      - project
    depends_on:
      - psql-db
  psql-db:
    container_name: psql-db
    image: "postgres:15"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "project"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - project

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    expose:
      - "4200"
    environment:
      - MOD=dev
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - spring-app
    networks:
      - project
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    networks:
      - project
    ports:
      - "9090:9090"
    volumes:
      - ./backend/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    networks:
      - project
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./backend/monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
  
networks:
  project:
    driver: bridge

volumes:
  postgres-db:
    driver: local